services:
  elan-api:
    build:
      context: .
      dockerfile: api/Dockerfile
    image: react-flask-app-api
    ports:
      - 5050:5050
    networks:
      - elan-network

networks:
  elan-network:
    driver: bridge
