services:
  api:
    build: .
    container_name: channel-api
    command: gunicorn -b :5000 api:app
    ports:
      - 5050:5050
    volumes:
      - .:/app
    networks:
      - elan-network

networks:
  elan-network:
    driver: bridge
