services:
  elan-api:
    build:
      context: .
      dockerfile: api/Dockerfile
    image: react-flask-app-api
    command: gunicorn -b :5050 'app.config:main()'
    ports:
      - 5050:5050
    networks:
      - elan-network
    volumes:
      - ./api:/app

  elan-ui:
    build:
      context: .
      dockerfile: ui/Dockerfile
    image: react-flask-app-ui
    command: npm run start
    ports:
      - 3000:3000
    networks:
      - elan-network
    volumes:
      - ./ui:/app
    depends_on:
      - elan-api
    links:
     - elan-api

networks:
  elan-network:
    driver: bridge
