name: tests
on:
  push:
    branches:
      - "**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov mypy pre-commit
          pip install -r api/requirements.txt
          pip install -e api
      - name: Test API  s
        run: |
          pytest --cov=app api/tests/
      - name: Run pre-commit checks
        uses: pre-commit/action@v3.0.0
