
name: tests
on:
  push:
    branches:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov mypy pre-commit
        pip install -r api/requirements.txt
        pip install -e api
    - name: Test APIs
      run: |
        pytest --cov=app api/tests/
    - name: Pre-commit checks
      run: |
        cd api && pre-commit run --all-files

